name: Verificar dependência de PR
on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: PR Check Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}